### ISSUE TITLE
bug: meter overflow on guide page? 

### ISSUE THREAD

**Issue by samuelstroschein** [jonathanharrell/hiq#114]
I assume the overflowing meters are a bug? (See the screenshot)

https://jonathanharrell.github.io/hiq/guide/meters-progress.html#meters

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/35429197/158870863-0a0817dd-92f7-45d9-af9d-dd825bebfc86.png">

**Comment by jonathanharrell** [comment]
Fixed in https://github.com/jonathanharrell/hiq/pull/116
