### ISSUE TITLE
[Idea] Automatically fix dependencies version number

### ISSUE THREAD

**Issue by equinusocio** [jonathanharrell/hiq#12]
I think it's better having a fixed dependencies version that will prevent inconsistency when development. To do that we have to add a `.npmrc` file that contains these rules:

```
git-tag-version = false
tag-version-prefix =
save-exact = true
progress = true
```

Or a `.yarnrc` file:

```
save-exact true
save-prefix false
```

These files will fix the dependencies version number during add/install but we have to manually fix the current dependencies version numbers in the `package.json`

**Comment by jonathanharrell** [comment]
Yep, agreed. I will assign this one to you if you don't mind.

**Comment by equinusocio** [comment]
👍🏻
