### ISSUE TITLE
[Idea] Use postcss-cssnext custom-selectors

### ISSUE THREAD

**Issue by equinusocio** [jonathanharrell/hiq#15]
Hi, maybe can be useful using [custom-selectors](http://cssnext.io/features/#custom-selectors) to group selectors inside components to easily switch to classes if required or update the selectors.

**Comment by jonathanharrell** [comment]
Nice. Will look into doing for v2.

**Comment by equinusocio** [comment]
There is a commit?

**Comment by jonathanharrell** [comment]
c6de3b6782b526147b89638ab8e4c244c7e282ab

**Comment by jonathanharrell** [comment]
38138f815527927608266734f3916bf386dfd8c8

**Comment by equinusocio** [comment]
👍🏻
