### ISSUE TITLE
Add more utility classes + mixins

### ISSUE THREAD

**Issue by wad3g** [jonathanharrell/hiq#16]
Further expanding #7 including an additional change to the utility classes.

##### Add namespaces to utility classes
Use namespacing for utility classes by prefixing them with `u-`. Each class has a specific role that shouldn't be added to or changed, may be used on an UI element, allows for improved organization of source files, and makes for easy recognition.

Also, some stateful namespaces are already present (`.is-primary`, `.is-fluid`). 

##### Add more utility classes
It would obviously be extremely easy to go overboard adding utility classes, but I've found a few of the following *pretty* useful in my experience: 

- `.u-full-width` 
- `.u-max-full-width` 
- `.u-pull-left` 
- `.u-pull-right` 
- `.u-center-block`
- `.u-hidden`

**Comment by equinusocio** [comment]
Consider that using classes for components status change is a bad practice and we should use aria-attributes following the specs

**Comment by jonathanharrell** [comment]
There is a `visually-hidden` class currently that hides elements from all devices except screen readers (this will change to `is-visually-hidden` in v2).

I like these and will incorporate into v2 (according to our naming convention):

`is-full-width`
`is-max-full-width`
`is-pulled-left`
`is-pulled-right`

Can you clarify what `u-center-block` does?

**Comment by wad3g** [comment]
`.center-block` sets an element to `display: block` and centers it by setting the margins to auto.

```
.center-block {
  display: block;
  margin-left: auto;
  margin-right: auto;
}
```

**Comment by jonathanharrell** [comment]
Ok makes sense.

**Comment by equinusocio** [comment]
What about centering without the display block? I could center a display flex item with just margin auto.

**Comment by jonathanharrell** [comment]
Yeah true. Maybe there should be an `is-centered` class that just applies margin auto to an element.

**Comment by wad3g** [comment]
Using `.is-centered` with flexbox doesn't make as much sense, in my opinion.

If using flexbox you're more than likely going to be centering content with `align-items: center` or `justify-content: center` rather than trying to center using margins.

**Comment by equinusocio** [comment]
Justify-content and align-items are use to center the inside content, not the container.

**Comment by jonathanharrell** [comment]
@wad3g think of this example:

```
div {
    display: flex;
    max-width: 30rem;
    margin-right: auto;
    margin-left: auto;
}
```

Here I want to center the parent flex element, in which case I can use margin auto.
