### ISSUE TITLE
[Idea] Use aria attributes for presentational changes

### ISSUE THREAD

**Issue by equinusocio** [jonathanharrell/hiq#17]
According to the spec we should use aria attributes widget (not css classes) to handle components presentational changes and utilities classes, like ~`[aria-hidden]` (should replace `.is-visually-hidden`)~, `aria-selected` and so on..

**Here the MDN article section**
https://developer.mozilla.org/en-US/docs/Web/Accessibility/An_overview_of_accessible_web_applications_and_widgets#Presentational_changes

There are many aria attributes available. 

**Here a full list of widget attributes**
https://www.w3.org/TR/wai-aria/#attrs_widgets

**Comment by jonathanharrell** [comment]
I think the use cases are slightly different. `[aria-hidden]` tells a screen reader to ignore an element, whereas `.is-visually-hidden` is hiding from users but still making element accessible to screen readers (for example, in the case of checkbox or radio inputs where I am overlaying pseudo-elements on top of the input for custom styling).

**Comment by equinusocio** [comment]
Right, but for other cases i think we can use aria attributes.

**Comment by jonathanharrell** [comment]
Certainly something we can suggest in the documentation. I'm not sure if it makes sense to apply default styling to aria attributes since there is a large range of use cases, but if you have specific examples please share. Thanks!

**Comment by equinusocio** [comment]
From the previous link:
> Developers should use ARIA states to indicate the state of UI widget elements and use CSS attribute selectors to alter the visual appearance based on the state changes (rather than using script to change a class name on the element).

WAI-ARIA was made for accessibility, but we can start to use them just for components status changes

**Comment by jonathanharrell** [comment]
Is there an example of a current status change in Hi-Q that you are thinking of that should use an aria attribute?

**Comment by equinusocio** [comment]
All `:disabled` and `:checked` should become `:disabled, [aria-disabled]` and `:checked, [aria-checked]`.. and so on.

**Comment by jonathanharrell** [comment]
Sure, that makes sense with custom controls. In that case, should we add `[role='checkbox']` alongside `input[type='checkbox`]?

**Comment by equinusocio** [comment]
Role checkbox define a semantic checkbox control that can be visually different from an input checkbox. For now we can just think about component statuses

**Comment by jonathanharrell** [comment]
I think the same could technically be true of `[role='button']` as well, but I still like that as a way of applying button styling to anchor elements. In any case, I think the logic here is sound and we can look at adding the aria attributes in v2.

**Comment by jonathanharrell** [comment]
Added `[aria-disabled]` and `[aria-checked]` in 0848abbd2fa6ac6fd72b981af9236f2958dbccb9. Feel free to add additional aria attributes where you think it's necessary.

**Comment by jonathanharrell** [comment]
Syntax fixed in 17ee7885f8c2f568f6425e42cd5ed030dd31043d.
