### ISSUE TITLE
Differentiate links from buttons

### ISSUE THREAD

**Issue by equinusocio** [jonathanharrell/hiq#20]
Hi, i think that the button style should style only buttons elements `<button>` and not `.button`.
A link element should not be used as a button (and should not have a button style).

Semantically a button is a button and a link is an inline hyperlinked text. My suggestion is to remove `.button` classname and relative styles/fix (`:visited` etc..) from the `button.css` component. What do you think @jonathanharrell

**Comment by jonathanharrell** [comment]
Styling a link to look like a button is a common use case that I would like to keep. Doesn't affect semantics but is something that is needed quite often.

**Comment by equinusocio** [comment]
Commons does not mean good. :) This was a practice from years with Web 2.0. Now technologies allow us to be more specific and semantic. A link element can be treated as button **ONLY** if a `role="button"` is present. We can change the web by improve what does not work anymore.

The goal of this issue is to remove `.button` class and use instead the `[role="button"]` attribute selector.

**Comment by jonathanharrell** [comment]
You've convinced me. :) `role="button"` will be better than applying a class. I will modify for v2.

**Comment by jonathanharrell** [comment]
Closed with 805b6879dde3bc311465e02f33430213d6ca657c.

**Comment by equinusocio** [comment]
What about a.btn.disabled?

**Comment by jonathanharrell** [comment]
Not sure what you mean. `disabled` is not a valid attribute on `a` element.

**Comment by equinusocio** [comment]
I mean a.btn what is? If we removed .button a.btn will not exist, right?

**Comment by jonathanharrell** [comment]
Sorry, just saw what you were referring to. I will remove that.
