### ISSUE TITLE
[Idea] Improve css dependencies for each component.

### ISSUE THREAD

**Issue by equinusocio** [jonathanharrell/hiq#21]
@jonathanharrell I think we need an improved dependencies system between components.

**Use case 1:**
Users can use all HIQ components by importing  `node_modules/hiq/css/hiq.css`

**Use case 2:**
Users can import a single components from hiq by importing `node_modules/hiq/css/elements/button.css`

Now we cover only the first use-case. I think we can cover the second one by let single components importing its css dependencies.

Eg.
If the `button.css` needs some variables and common mixins it should import them inside its file. So importing the single component will import the dependencies it needs.

**Comment by jonathanharrell** [comment]
Yeah that would be nice. I think there is still a need to import a base file first. Something like:

`@import 'node_modules/hiq/css/base.css'`
`@import 'node_modules/hiq/css/button.css'`

Base would include setup of type scale and a few global resets.

I can work on refactoring element files to import the mixins they need.

**Comment by equinusocio** [comment]
Why you can't import `base.css` inside each component?

**Comment by jonathanharrell** [comment]
`base.css` would contain global typographic styling and some structural styles on html, body, etc. Not just vars. So it's not really something that could be split up between components and it wouldn't make sense to repeat for each component.

**Comment by equinusocio** [comment]
Ok. I think the point should be that if you import all the hi-q framework you will have this base.css included. But if you import only the button component you don’t need the whole typography settings. So i think you should be able to import base.css as well, as a separate “piece” of hi-q.

1. Import all hi-q
2. Import button.css component only
3. Import button.css and base.css (that i think should be broken up in separate files)

**Comment by jonathanharrell** [comment]
Yeah that could work. And for v2 custom properties are set up so they always have a fallback, so I think that would work fine for importing components separately.

**Comment by equinusocio** [comment]
👍🏻 I will fix dependencies version tomorrow.

**Comment by jonathanharrell** [comment]
Closed with b2239113f36d0fb3e547a61c7a4407b014c3ea52.
