### ISSUE TITLE
Select Multiple Background Gradient Not Applying

### ISSUE THREAD

**Issue by jonathanharrell** [jonathanharrell/hiq#29]
Noticed this code from `selects.pcss` seem to be applying:

```
select {
&[multiple] {
    & option:checked {
      background: var(--color-primary, hsl(210, 100%, 50%)) -webkit-linear-gradient(bottom, var(--color-primary, hsl(210, 100%, 50%)) 0%, var(--color-primary, hsl(210, 100%, 50%)) 100%);
    }
  }
}
```

I can change the background to any value in multiple browsers and it just uses the browser default color.

**Comment by equinusocio** [comment]
I tested this code and it works on every browser  but firefox. I will test it again later.

**Comment by jonathanharrell** [comment]
Maybe I'm missing something, but here in Chrome I'm defining the background as red but I see no visual effect.

<img width="1015" alt="screenshot 2017-11-17 08 37 32" src="https://user-images.githubusercontent.com/28496164/32952366-afa154ec-cb72-11e7-8980-72bf6aa0f511.png">

**Comment by equinusocio** [comment]
@jonathanharrell Yes because `background: COLOR` doesn't work. If you see the code we are using a linear-gradient with the same color. Linear gradient is the only thing that work.

**Comment by jonathanharrell** [comment]
ah gotcha - fun little hack there. :)
