### ISSUE TITLE
Link from node_modules does not work

### ISSUE THREAD

**Issue by equinusocio** [jonathanharrell/hiq#3]
Hi, this is the best modern framework that i saw until now. Awesome work.

One suggestion, linking a file from **node_modules** will not work because `node_modules` should be exposed as static folder... and no ones do it (and no one should do it). So i suggest you to remove this snippet from the readme.

```html
<link rel="stylesheet" href="node_modules/hiq/hiq.css">
<link rel="stylesheet" href="node_modules/hiq/hiq.min.css">
```

@jonathanharrell Let me know if you are open to PR and i will make some improvements :)

**Comment by jonathanharrell** [comment]
Thanks! Yes, the readme should be changed. Feel free to submit a PR. FYI, I am currently working on a v2 that will provide some more utility classes and improve the way the variable overrides work.

**Comment by equinusocio** [comment]
@jonathanharrell i will take a look at the branch. Can i open some some issues to talk about some ideas?

**Comment by jonathanharrell** [comment]
Yes, please do.
