### ISSUE TITLE
[enhancement] Indeterminate progress

### ISSUE THREAD

**Issue by equinusocio** [jonathanharrell/hiq#31]
> Indeterminate progress bar styling currently only works in Chrome.

False :P You can make it works on Safari, Webkit-based and Firerfox. i don't have tested it on Edge yet.

Check this (my) live example :)
https://ne-progress.stackblitz.io

Here the code:
https://github.com/equinusocio/native-elements/blob/develop/elements/ne-progress/src/ne-progress.pcss

**Comment by jonathanharrell** [comment]
Ok great. Will look. Thanks!

**Comment by jonathanharrell** [comment]
Resolved by d8323d189917e02d59c2739f99180684f721ab0c.
