### ISSUE TITLE
[enhancement] <meter> element

### ISSUE THREAD

**Issue by equinusocio** [jonathanharrell/hiq#32]
Hi @jonathanharrell i think that the `<meter>` element style should reflect his functionality. The meter is not visually a progress bar, it should display different feedbacks based on his attributes. You can style it on Firefox, webkit-based and chrome.

Check this live example from native-elements
https://ne-meter.stackblitz.io/

Here the code:
https://github.com/equinusocio/native-elements/blob/master/elements/ne-meter/src/ne-meter.pcss#L33-L70

**Comment by jonathanharrell** [comment]
Updated in 57e4c5b4d72d4cbd9881a74ab95871f1ceab7b5c.

**Comment by equinusocio** [comment]
I think that weak, good and strong are more corrects as variable name intead of success, error etc.. :)
