### ISSUE TITLE
Nested at-rules upcoming issue

### ISSUE THREAD

**Issue by equinusocio** [jonathanharrell/hiq#35]
Hi @jonathanharrell. As you can see on the [postcss-nesting](https://github.com/jonathantneal/postcss-nesting) plugin from the next major release it will drop the support to nested at-rules, including media queries.

> NOTICE: In v7.0.0 nesting at-rules like @media will no longer work, as they are not part of the nesting proposal.

This will introduce several braking changes if updated.

**Comment by jonathanharrell** [comment]
Thanks for the heads up! I will probably replace with the [postcss-nested](https://github.com/postcss/postcss-nested) plugin.

**Comment by jonathanharrell** [comment]
Resolved in 26596547f27760814b0d5c38f7c5b46f5f9a681f.
