### ISSUE TITLE
Typo in doc

### ISSUE THREAD

**Issue by equinusocio** [jonathanharrell/hiq#36]
Hi Jonathan, there is a little typo in this doc page
https://jonathanharrell.github.io/hiq/guide/typography.html#responsive-typography

<img width="610" alt="screenshot 2019-01-10 at 15 16 11" src="https://user-images.githubusercontent.com/10454741/50974078-b00c2700-14ea-11e9-905a-46766de853c8.png">

The bottom right custom property should be `--hiq-unitless-upper-font-range` instead of `--hiq-unitless-lower-font-range` i can't make a PR since is an image.

**Comment by jonathanharrell** [comment]
Thanks for catching this! Fixed in 55ecbee61e0d0b191d61ac8faa6f5a7bcbd8a78e.
