### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by jonathanharrell** [jonathanharrell/hiq#8]
* Migrate to Github pages?
* Basic vs. advanced usage (PostCSS plugin requirements, providing fallbacks, etc.)
* Browser support
* Utility classes
* Mixins if using PostCSS (required to change custom media queries)
* New variables

**Comment by equinusocio** [comment]
For the first point, what about https://docs.catalog.style?

**Comment by jonathanharrell** [comment]
Better documentation now available on v2 branch. Will continue to update as tweaks are made to framework. Using Github Pages due to good integration with Github.
